symfony/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_SLUG', fields: ['slug'])]
#[ORM\HasLifecycleCallbacks]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Toto pole je povinné.')]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'Toto pole je povinné.')]
    private ?string $content = null;

    #[ORM\Column(length: 512, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $date_created = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?Category $category = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'post', orphanRemoval: true)]
    #[ORM\OrderBy(['id' => 'DESC'])]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setDateCreatedValue(): void
    {
        $this->date_created = new \DateTimeImmutable();
    }

    public function createSlug(SluggerInterface $slugger): void
    {
        $this->slug = $slugger->slug($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeImmutable
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeImmutable $date_created): static
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

symfony/src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Post;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Název článku'
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Obsah',
                'attr' => ['rows' => 10]
            ])
            ->add('image', FileType::class, [
                'label' => false,
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*'],
                'constraints' => [
                    new Image()
                ]
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Kategorie'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

symfony/src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\DeletePostType;
use App\Form\PostType;
use App\Repository\CategoryRepository;
use App\Repository\PostRepository;
use App\Service\ImageUploader;
use App\Utils\PaginationData;
use App\Utils\ReadingTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapQueryString;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\UnicodeString;

class PostController extends AbstractController
{
    public function __construct(
        private PostRepository $postRepository,
        private EntityManagerInterface $entityManager
    ) {
    }

    #[Route('/prispevky/{slug}', name: 'app_posts')]
    public function index(Request $request, CategoryRepository $categoryRepository, string $slug = ''): Response
    {
        if ($slug) {
            $category = $categoryRepository->findOneBy(['slug' => $slug]);
        }

        $page = max(1, $request->query->getInt('page', 1));
        $offset = ($page - 1) * PostRepository::POSTS_PER_PAGE;
        $paginator = $this->postRepository->getPaginatior($category ?? null, $offset);
        $paginationData = new PaginationData(PostRepository::POSTS_PER_PAGE, $paginator->count(), $page);

        return $this->render('post/index.html.twig', [
            'category' => $category ?? null,
            'posts' => $paginator,
            'pagination_data' => $paginationData,
        ]);
    }

    #[Route('/prispevek/{slug}', name: 'app_post')]
    public function show(Request $request, Post $post): Response
    {
        $redingTime = ReadingTime::calculate($post->getContent());

        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);

        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $post->addComment($comment);

            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            $this->addFlash('success', 'Komentář byl úspěšně vytvořen.');

            return $this->redirectToRoute('app_post', ['slug' => $post->getSlug()]);
        }

        if ($commentForm->isSubmitted() && !$commentForm->isValid()) {
            $this->addFlash('error', 'Komentář se nepodařilo vytvořit. Zkontrojte správnost vyplnených informací.');
        }

        return $this->render('post/show.html.twig', [
            'post' => $post,
            'reading_time' => $redingTime,
            'comment_form' => $commentForm,
        ]);
    }

    #[Route('/api/prispevky/{slug}', name: 'api_posts')]
    public function apiIndex(Request $request, CategoryRepository $categoryRepository, string $slug = ''): Response
    {
        if ($slug) {
            $category = $categoryRepository->findOneBy(['slug' => $slug]);
        }

        $page = max(1, $request->query->getInt('page', 1));
        $offset = ($page - 1) * PostRepository::POSTS_PER_PAGE;
        $paginator = $this->postRepository->getPaginatior($category ?? null, $offset);
        $paginationData = new PaginationData(PostRepository::POSTS_PER_PAGE, $paginator->count(), $page);

        $processedPosts = array_map(
            function ($post) {
                $content = (new UnicodeString(strip_tags($post->getContent())))->truncate(80, '...');
                $url = $this->generateUrl('app_post', ['slug' => $post->getSlug()]);
                return [
                    'name' => $post->getName(),
                    'image' => '/images/' . $post->getImage(),
                    'content' => $content,
                    'url' => $url
                ];
            },
            $paginator->getQuery()->getResult()
        );

        return $this->json([
            'posts' => $processedPosts,
            'pagination' => $paginationData
        ]);
    }

    #[Route('/admin/prispevky', name: 'app_posts_admin')]
    public function indexAdmin(Request $request): Response
    {
        $page = max(1, $request->query->getInt('page', 1));
        $offset = ($page - 1) * PostRepository::POSTS_PER_PAGE;
        $paginator = $this->postRepository->getPaginatior(null, $offset);
        $paginationData = new PaginationData(PostRepository::POSTS_PER_PAGE, $paginator->count(), $page);

        return $this->render('post/index_admin.html.twig', [
            'posts' => $paginator,
            'pagination_data' => $paginationData,
        ]);
    }

    #[Route('/admin/prispevky/novy', name: 'app_create_post_admin')]
    public function create(Request $request, ImageUploader $imageUploader): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post->setAuthor($this->getUser());

            $image = $form->get('image')->getData();
            $imageUploadError = false;

            if ($image) {
                $imageName = $imageUploader->upload($image);
                $post->setImage($imageName);
                $imageUploadError = !$imageName;
            }

            $this->entityManager->persist($post);
            $this->entityManager->flush();

            if ($imageUploadError) {
                $this->addFlash('error', 'Článek byl úspěšně přidán, ale nepodařilo se nahrát obrázek.');
            } else {
                $this->addFlash('success', 'Článek byl úspěšně přidán.');
            }

            return $this->redirectToRoute('app_edit_post_admin', ['slug' => $post->getSlug()]);
        }

        return $this->render('post/create.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/admin/prispevky/{slug}/uprava', name: 'app_edit_post_admin')]
    public function edit(
        Request $request,
        Post $post,
        ImageUploader $imageUploader,
        ParameterBagInterface $parameterBag
    ): Response {
        $editForm = $this->createForm(PostType::class, $post);
        $deleteForm = $this->createForm(DeletePostType::class);

        $editForm->handleRequest($request);
        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $oldImage = $post->getImage();
            $image = $editForm->get('image')->getData();
            $imageUploadError = false;

            if ($image) {
                $imageName = $imageUploader->upload($image);
                $post->setImage($imageName);
                $imageUploadError = !$imageName;
            }

            if (!$imageUploadError && $oldImage) {
                $imagesDirectory = $parameterBag->get('image_directory');
                unlink("$imagesDirectory/$oldImage");
            }

            $this->entityManager->persist($post);
            $this->entityManager->flush();

            if ($imageUploadError) {
                $this->addFlash('error', 'Článek byl úspěšně upraven, ale nepodařilo se nahrát obrázek.');
            } else {
                $this->addFlash('success', 'Článek byl úspěšně upraven.');
            }

            return $this->redirectToRoute('app_edit_post_admin', ['slug' => $post->getSlug()]);
        }


        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'edit_form' => $editForm,
            'delete_form' => $deleteForm
        ]);
    }

    #[Route('/admin/prispevky/{slug}/odstraneni', name: 'app_delete_post_admin', methods: ['POST'])]
    public function destroy(Request $request, Post $post, ParameterBagInterface $parameterBag): Response
    {
        $form = $this->createForm(DeletePostType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($post->getImage()) {
                unlink($parameterBag->get('image_directory') . '/' . $post->getImage());
            }

            $this->entityManager->remove($post);
            $this->entityManager->flush();

            $this->addFlash('success', 'Článek byl odstraněn.');
            return $this->redirectToRoute('app_posts_admin');
        }

        $this->addFlash('error', 'Článek se nepodařilo odstranit.');
        return $this->redirectToRoute('app_edit_post_admin', ['slug' => $post->getSlug()]);
    }
}

symfony/templates/post/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'components/protected/navbar.html.twig' %}
    
    <main class="main-admin">
            <h1>Nový článek</h1>
            {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.content) }}
                {{ form_row(form.category) }}
                {{ form_row(form.image) }}
                <div>
                    <button type="submit">Přidat článek</button>
                </div>
            {{ form_end(form) }}
    </main>
{% endblock %}

symfony/templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'components/protected/navbar.html.twig' %}
    
    <main class="main-admin">
            <h1>Úpráva: {{ post.name }}</h1>
            {{ form_start(edit_form) }}
                {{ form_row(edit_form.name) }}
                {{ form_row(edit_form.content) }}
                {{ form_row(edit_form.category) }}
                {{ form_row(edit_form.image) }}
                <img src="{{ asset('images/' ~ post.image) }}" alt="{{ post.name }}" />
                <div style="flex-direction: row">
                    <button type="button" data-otevri-dialog="delete-post">Odstranit článek</button>
                    <button type="submit">Upravit článek</button>
                </div>
            {{ form_end(edit_form) }}

            <dialog id="delete-post">
               <div class="obsah-dialogu">
                    <p>Opravdu chete odstranit tento článek?</p>
                    {{ form_start(delete_form, {
                        action: path('app_delete_post_admin', {slug: post.slug})
                    }) }}
                    <div style="display: flex; flex-direction: row; justify-content: space-between">
                        <button style="width: auto; margin-left: 0;" type="button" data-zavri-dialog="delete-post">Zrušit
                        </button>
                        <button type="submit" class="odstraneni"
                                style="width: auto; margin-left: 0;">Odstranit
                        </button>
                    </div>
                    {{ form_end(delete_form) }}
                </div>
            </dialog>
    </main>
{% endblock %}

symfony/templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'components/public/header.html.twig' %}
    
    <main class="vypis-clanku">
        <h1>{{ category ? category.name : 'Všechny příspěvky' }}</h1>
        
        <div id="clanky">
            {% for post in posts %}
                {% include 'components/public/post_card.html.twig' %}
            {% endfor %}
        </div>

        <div class="vypis-clanku-tlacitka">
            <button id="nacti-clanky" type="button" data-slug="{{ category ? category.slug : '' }}">Načíst další články</button>
        </div>

        <div class="vypis-clanku-tlacitka">
            <a id="predchozi" href="{{ path('app_posts', {slug: category ? category.slug : null, page: pagination_data.previousPage}) }}" 
            {% if not pagination_data.hasPreviousPage %}
                class="vypnuto" aria-disabled="true"
            {% endif %}
            >Předchozí</a>
            <a id="dalsi" href="{{ path('app_posts', {slug: category ? category.slug : null, page: pagination_data.nextPage}) }}"
            {% if not pagination_data.hasNextPage %}
                class="vypnuto" aria-disabled="true"
            {% endif %}
            >Další</a>
        </div>
    </main>

    {% include 'components/public/footer.html.twig' %}
{% endblock %}

symfony/templates/post/index_admin.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'components/protected/navbar.html.twig' %}
    
    <main class="vypis-clanku main-admin">
        <div class="nadpis-admin">
            <h1>Příspěvky</h1>
            <a href="{{ path('app_create_post_admin') }}" class="tlacitko">Přidat článek</a>
        </div>
        
        <div id="clanky">
            {% for post in posts %}
                {% include 'components/protected/post_card.html.twig' %}
            {% endfor %}
        </div>

        <div class="vypis-clanku-tlacitka">
            <a id="predchozi" href="{{ path('app_posts', {page: pagination_data.previousPage}) }}" 
            {% if not pagination_data.hasPreviousPage %}
                class="vypnuto" aria-disabled="true"
            {% endif %}
            >Předchozí</a>
            <a id="dalsi" href="{{ path('app_posts', {page: pagination_data.nextPage}) }}"
            {% if not pagination_data.hasNextPage %}
                class="vypnuto" aria-disabled="true"
            {% endif %}
            >Další</a>
        </div>
    </main>
{% endblock %}

symfony/templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.name }}{% endblock %}

{% block body %}
    {% include 'components/public/header.html.twig' %}
    
    <main>
        <section class="clanek">
            <header>
                <h1>{{ post.name }}</h1>
                <p>
                    <i>{{ post.author.name }}</i>
                    <i>{{ post.dateCreated|date('d. m. Y') }}</i>
                    <i>{{ reading_time }} min. čtení</i>
                </p>
            </header>
            <article>
                {{ post.content|raw }}
                <img src="{{ asset('images/' ~ post.image) }}" alt="{{ post.name }}">
            </article>
        </section>

        <section class="komentare">
            <h2>Komentáře</h2>

            {% for comment in post.comments %}
                {% include 'components/public/comment.html.twig' %}
            {% endfor %}

            {{ form(comment_form) }}
        </section>
    </main>

    {% include 'components/public/footer.html.twig' %}
{% endblock %}